/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.0.2/userguide/multi_project_builds.html
 */

rootProject.name = "gradle-feature-capabilities-in-composite-build"
includeBuild("include-one") {
    dependencySubstitution {
        substitute(module("com.myorg:utilities-caching-support"))
            .with(variant(project(":utilities")) {
                capabilities {
                    requireCapability("com.myorg:utilities-caching-support")
                }
            })
    }
}
include("app")
