/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.myorg.app;

import com.myorg.list.LinkedList;

import static com.myorg.utilities.StringUtils.join;
import static com.myorg.utilities.StringUtils.split;
import static com.myorg.app.MessageUtils.getMessage;

import com.myorg.utilities.CacheWrapper;
import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
        CacheWrapper cacheWrapper = new CacheWrapper();
        System.out.println(cacheWrapper.getCachedValue("abcd"));
    }
}
