/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `application`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-text:1.9")
    implementation(module("com.myorg", "utilities"))
    implementation(module("com.myorg", "utilities")) {
        capabilities {
            requireCapability("com.myorg:utilities-caching-support")
        }
    }
    implementation(module("com.myorg:utilities-caching-support"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")
}

application {
    // Define the main class for the application.
    mainClass.set("com.myorg.app.App")
}
