/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}
group="com.myorg"

java {
    java {
        registerFeature("cachingSupport") {
            usingSourceSet(sourceSets["main"])
        }
    }
}

dependencies {
    api(project(":list"))
    "cachingSupportImplementation"("com.google.guava:guava:30.1.1-jre")
}
